version: '3.8'

services:
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile
      # target: ${STAGE:-testing}
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules

